annotations:
  artifacthub.io/changes: |
    - "âœ¨ update chart to version 0.0.12"
apiVersion: v2
appVersion: v0.0.12
description: Kubescape integration with Prometheus
home: https://www.armosec.io/
maintainers:
- email: ben@armosec.io
  name: Ben Hirschberg
  url: https://www.linkedin.com/in/benyamin-ben-hirschberg-66141890
- email: dw@armosec.io
  name: David Wertenteil
  url: https://www.linkedin.com/in/david-wertenteil-0ba277b9
- email: bez@armosec.io
  name: Bezalel Brandwine
  url: https://www.linkedin.com/in/bezalel-brandwine
name: kubescape-prometheus-integrator
type: application
version: 0.0.2