apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: tekton-triggers-core-interceptors
    app.kubernetes.io/component: interceptors
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "v0.22.1"
    app.kubernetes.io/part-of: tekton-triggers
    triggers.tekton.dev/release: "v0.22.1"
    app: tekton-triggers-core-interceptors
    version: "v0.22.1"
  name: tekton-triggers-core-interceptors
  namespace: '{{ .Release.Namespace }}'
spec:
  ports:
    - name: "https"
      port: 8443
  selector:
    app.kubernetes.io/name: core-interceptors
    app.kubernetes.io/component: interceptors
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-triggers

