apiVersion: v2
appVersion: 1.16.0
description: A Helm chart for Monitoring
name: monitoring
type: application
version: 0.1.9
dependencies:
  - name: prometheus-msteams 
    condition: prometheus-msteams.enabled
    version: 1.0.0
    repository: https://kube-tarian.github.io/helmrepo-supporting-tools/