annotations:
  artifacthub.io/changes: |
    - "âœ¨ update chart to version 104"
apiVersion: v2
appVersion: v2.8.0-rc2
description: An operator for synthetic test and monitoring. Works great with Prometheus.
home: https://kuberhealthy.github.io/kuberhealthy/
icon: https://raw.githubusercontent.com/kuberhealthy/kuberhealthy/master/images/logo-square.png
keywords:
- kuberhealthy
- kubernetes
- operator
- monitoring
- synthetic
- testing
- comcast
- health
- prometheus
maintainers:
- email: ericgreer@gmail.com
  name: integrii
- email: jonathan_phan@comcast.com
  name: jonnydawg
- email: joshulyne_park@comcast.com
  name: joshulyne
name: kuberhealthy
sources:
- https://github.com/kuberhealthy/kuberhealthy
- https://github.com/kuberhealthy/kuberhealthy/tree/master/deploy/helm/kuberhealthy
type: application
version: 1.0.1
