annotations:
  artifacthub.io/changes: |
    - "âœ¨ update chart to version 47.0.0"
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/prometheus-community/helm-charts
    - name: Upstream Project
      url: https://github.com/prometheus-operator/kube-prometheus
  artifacthub.io/operator: "true"
apiVersion: v2
appVersion: v0.66.0
dependencies:
- condition: kubeStateMetrics.enabled
  name: kube-state-metrics
  repository: https://prometheus-community.github.io/helm-charts
  version: 5.7.*
- condition: nodeExporter.enabled
  name: prometheus-node-exporter
  repository: https://prometheus-community.github.io/helm-charts
  version: 4.17.*
- condition: grafana.enabled
  name: grafana
  version: 1.0.*
  repository: https://kube-tarian.github.io/helmrepo-supporting-tools/
description: kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards,
  and Prometheus rules combined with documentation and scripts to provide easy to
  operate end-to-end Kubernetes cluster monitoring with Prometheus using the Prometheus
  Operator.
home: https://github.com/prometheus-operator/kube-prometheus
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
keywords:
- operator
- prometheus
- kube-prometheus
kubeVersion: '>=1.16.0-0'
maintainers:
- email: andrew@quadcorps.co.uk
  name: andrewgkew
- email: gianrubio@gmail.com
  name: gianrubio
- email: github.gkarthiks@gmail.com
  name: gkarthiks
- email: kube-prometheus-stack@sisti.pt
  name: GMartinez-Sisti
- email: scott@r6by.com
  name: scottrigby
- email: miroslav.hadzhiev@gmail.com
  name: Xtigyro
- email: quentin.bisson@gmail.com
  name: QuentinBisson
name: kube-prometheus-stack
sources:
- https://github.com/prometheus-community/helm-charts
- https://github.com/prometheus-operator/kube-prometheus
type: application
version: 1.0.10
