annotations:
  artifacthub.io/changes: |
    - "âœ¨ update chart to version 3.10.0"
apiVersion: v2
appVersion: 2.7.0
dependencies:
- alias: minio
  condition: minio.enabled
  name: minio
  repository: https://kube-tarian.github.io/helmrepo-supporting-tools/
  version: 1.0.0
- alias: grafana-agent-operator
  condition: monitoring.selfMonitoring.grafanaAgent.installOperator
  name: grafana-agent-operator
  repository: https://kube-tarian.github.io/helmrepo-supporting-tools/
  version: 1.0.0
description: Helm chart for Grafana Loki in simple, scalable mode
home: https://grafana.github.io/helm-charts
icon: https://grafana.com/docs/loki/latest/logo_and_name.png
maintainers:
- name: trevorwhitney
- name: jeschkies
name: loki
sources:
- https://github.com/grafana/loki
- https://grafana.com/oss/loki/
- https://grafana.com/docs/loki/latest/
type: application
version: 1.0.0
