apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: image-verification
spec:
  validationFailureAction: Enforce
  webhookTimeoutSeconds: 30
  rules:
    - name: image-verification
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
        - "ghcr.io/intelops/*/*:*"
        attestors:
        - entries:
          - keyless:
              subject: "https://github.com/*/*/.github/workflows/*@refs/heads/main"
              issuer: "https://token.actions.githubusercontent.com"
              rekor:
                url: https://rekor.sigstore.dev
