apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: {{ include "monitoring.fullname" . }}-cstor
spec:
  endpoints:
  - path: /metrics
    port: exporter
    metricRelabelings:
      - action: replace
        regex: .*
        replacement: {{ .Values.clustername }}
        separator: ;
        targetLabel: cluster_name
    relabelings:
    - action: keep
      regex: volume_exporter_prometheus
      sourceLabels:
      - __meta_kubernetes_pod_label_monitoring
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_label_vsm
      targetLabel: openebs_pv
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_label_openebs_io_persistent_volume
      targetLabel: openebs_pv
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_label_openebs_io_persistent_volume_claim
      targetLabel: openebs_pvc
    - action: replace
      sourceLabels:
      - __meta_kubernetes_endpoints_label_openebs_io_cas_type
      targetLabel: openebs_cas_type
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      openebs.io/cas-type: cstor
